use_frameworks!

target 'YFPodDemo_Example' do
  pod 'YFPodDemo', :path => '../'

  target 'YFPodDemo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
